version: '3.8'

services:
  db:
    container_name: db
    build: ./mysql
    ports: 
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    restart: always

  server:
    build: ./server
    ports: 
      - "80:80"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db
    restart: always
    