"""fix

Revision ID: 08c6b5fc01db
Revises: 04808c8f4b33
Create Date: 2022-10-28 11:08:37.062617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c6b5fc01db'
down_revision = '04808c8f4b33'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('credit_sum', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lines', 'credit_sum')
    # ### end Alembic commands ###
