version: "3.8"

services:
  api:
    image: orders_api:latest
    ports:
      - "8000:80"
    # command: uvicorn --reload --host 0.0.0.0 --port 8000 orders_api.main:app
    volumes:
      - ./backend:/workspace:z
      - ./backend/apache-vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db/orders_api_db"

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./backend:/workspace
    depends_on:
      - api

  db:
    image: postgres:13
    ports:
      - "2345:5432"
    # volumes:
    #   - ./backend/postgres/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "orders_api_db"
