version: "3.8"

services:
  db:
    image: mysql
    volumes:
      - ./myapp:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  server:
    build: ./server
    ports:
      - "80:80"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - db
    restart: always

volumes:
  myapp:
