version: "3.8"

services:
  api:
    build: .
    command: uvicorn --reload --host 0.0.0.0 --port 8000 src.main:app
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgresql://postgres:mypassword@db/bank_api"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 2345:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "bank_api"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
