"""lines

Revision ID: 04808c8f4b33
Revises: 2b2fd26809df
Create Date: 2022-10-28 11:06:38.204624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04808c8f4b33'
down_revision = '2b2fd26809df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'lines', 'accounts', ['account_id'], ['account_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_column('lines', 'account_id')
    # ### end Alembic commands ###
